# Generated by Django 5.1.6 on 2025-10-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
