# Generated by Django 5.1.6 on 2025-10-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exercice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fichier Excel'),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Année'),
        ),
    ]
