# Generated by Django 5.1.6 on 2025-03-07 17:35

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapportage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeRapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="rapportmensuel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rapportsemestriel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rapporttrimestriel",
            name="user",
        ),
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("file", models.FileField(upload_to="", verbose_name="Fichier")),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rapportage.typerapport",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="RapportAnnuel",
        ),
        migrations.DeleteModel(
            name="RapportMensuel",
        ),
        migrations.DeleteModel(
            name="RapportSemestriel",
        ),
        migrations.DeleteModel(
            name="RapportTrimestriel",
        ),
    ]
