# Generated by Django 5.1.6 on 2025-03-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapportage", "0002_typerapport_remove_rapportmensuel_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapport",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
