# Generated by Django 5.1.6 on 2025-03-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapportage", "0003_alter_rapport_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapport",
            name="file",
            field=models.FileField(upload_to="rapports", verbose_name="Fichier"),
        ),
        migrations.AlterField(
            model_name="rapport",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mensuel", "Mensuel"),
                    ("Trimestriel", "Trimestriel"),
                    ("Semestriel", "Semestriel"),
                    ("Annuel", "Annuel"),
                    ("Spécifique", "Spécifique"),
                    ("Autres", "Autres"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
