# Generated by Django 5.1.7 on 2025-03-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_role_user_role"),
        ("rapportage", "0004_alter_rapport_file_alter_rapport_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapport",
            name="departements",
            field=models.ManyToManyField(to="core.departement"),
        ),
        migrations.AddField(
            model_name="rapport",
            name="roles",
            field=models.ManyToManyField(to="core.role"),
        ),
        migrations.AddField(
            model_name="rapport",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
