# Generated by Django 5.1.7 on 2025-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rapportage", "0005_rapport_departements_rapport_roles_rapport_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rapport",
            name="label",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rapport",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mensuel-Projet", "Mensuel-Projet"),
                    ("Trimestriel-Projet", "Trimestriel-Projet"),
                    ("Mensuel-Programme", "Mensuel-Programme"),
                    ("Trimestriel-Programme", "Trimestriel-Programme"),
                    ("Semestriel", "Semestriel"),
                    ("Annuel", "Annuel"),
                    ("Circonstancier", "Circonstancier"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
