# Generated by Django 5.1.6 on 2025-03-16 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0026_remove_appuitechnique_sous_composant_and_more"),
        ("programme", "0002_activitemonth_delete_activitequarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="ppm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="ref_ddp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="ref_ddp_action",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="ref_ddp_activites",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="ref_ddp_ligne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="ref_ddp_nature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="activite",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activite",
            name="status_execution",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="planificationcoutprogram",
            name="cout_unitaire",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="planificationcoutprogram",
            name="exercice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.exercice",
            ),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="indicateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="programme.indicateurprogram",
            ),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="partenaire",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="activitemonth",
            name="label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tacheprogram",
            name="location",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tacheprogram",
            name="responsable",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
