# Generated by Django 5.1.6 on 2025-03-18 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_role_user_role"),
        ("programme", "0003_activite_ppm_activite_ref_ddp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.departement",
            ),
        ),
    ]
