# Generated by Django 5.1.6 on 2025-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0004_activite_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
