# Generated by Django 5.1.6 on 2025-03-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0006_composantesprogram_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicateurprogram",
            name="order",
            field=models.CharField(max_length=100),
        ),
    ]
