# Generated by Django 5.1.6 on 2025-03-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0007_alter_indicateurprogram_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tacheprogram",
            name="nature_economique",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="order",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="ppm",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="ref_ddp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="ref_ddp_action",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="ref_ddp_activites",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="ref_ddp_ligne",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="ref_ddp_nature",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tacheprogram",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
