# Generated by Django 5.1.6 on 2025-03-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "programme",
            "0008_tacheprogram_nature_economique_tacheprogram_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificationcoutprogram",
            name="montant",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
