# Generated by Django 5.1.6 on 2025-03-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0009_alter_planificationcoutprogram_montant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificationcoutprogram",
            name="quantity",
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
