# Generated by Django 5.1.6 on 2025-03-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0010_alter_planificationcoutprogram_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificationcoutprogram",
            name="frequence",
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
