# Generated by Django 5.1.6 on 2025-03-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0011_alter_planificationcoutprogram_frequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planificationcoutprogram",
            name="cout_unitaire",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="planificationcoutprogram",
            name="duree",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="planificationcoutprogram",
            name="unite",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
