# Generated by Django 5.1.6 on 2025-03-18 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0012_alter_planificationcoutprogram_cout_unitaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composantesprogram",
            name="sous_domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="programme.sousdomainresult",
            ),
        ),
    ]
