# Generated by Django 5.1.6 on 2025-10-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercice'),
        ('programme', '0013_composantesprogram_sous_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificationcoutprogram',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice'),
        ),
    ]
