# Generated by Django 5.1.6 on 2025-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0002_ppm_ild_souscomposant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="cout",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tache",
            name="cout",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activite",
            name="montant_engage",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="ptbaprojet",
            name="montant_total",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tache",
            name="montant_engage",
            field=models.PositiveBigIntegerField(),
        ),
    ]
