# Generated by Django 5.1.6 on 2025-03-06 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0003_activite_cout_tache_cout_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ild",
            name="souscomposant",
        ),
    ]
