# Generated by Django 5.1.6 on 2025-03-06 11:21

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0004_remove_ild_souscomposant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieDepense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("status", models.IntegerField(default=0)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ild",
            name="type",
            field=models.CharField(
                blank=True, choices=[(1, "Ild"), (2, "At")], max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="Indicateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[(1, "Ild"), (2, "At")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("status", models.IntegerField(default=0)),
                (
                    "sous_composant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planification.souscomposantprojet",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="rld",
            name="ild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="planification.indicateur",
            ),
        ),
    ]
