# Generated by Django 5.1.6 on 2025-03-07 12:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0005_categoriedepense_ild_type_indicateur_alter_rld_ild"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("montant", models.BigIntegerField(default=0)),
                ("status", models.IntegerField(default=0)),
                ("in_drf", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TypeProcedureAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypeUGP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypeUnite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="categoriedepense",
            options={},
        ),
        migrations.RemoveField(
            model_name="categoriedepense",
            name="created",
        ),
        migrations.RemoveField(
            model_name="categoriedepense",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="categoriedepense",
            name="status",
        ),
        migrations.AddField(
            model_name="tache",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tache",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tache",
            name="depends_on",
            field=models.ManyToManyField(
                blank=True, null=True, to="planification.tache"
            ),
        ),
        migrations.AddField(
            model_name="tache",
            name="frequence",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tache",
            name="indicateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.indicateur",
            ),
        ),
        migrations.AddField(
            model_name="tache",
            name="quantite",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tache",
            name="responsable",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ild",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("ILD", "Ild"), ("AT", "At")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="indicateur",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Indicateur_Lie_Decaissement", "Ild"),
                    ("Appui Technique", "Appui Technique"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tache",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.categoriedepense",
            ),
        ),
        migrations.AlterField(
            model_name="tache",
            name="montant_engage",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tache",
            name="ugp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.typeugp",
            ),
        ),
        migrations.AlterField(
            model_name="tache",
            name="unite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="planification.typeunite",
            ),
        ),
    ]
