# Generated by Django 5.1.6 on 2025-03-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "planification",
            "0006_decaissement_typeprocedureacquisition_typeugp_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tache",
            name="parent_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
    ]
