# Generated by Django 5.1.6 on 2025-03-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0007_tache_object_id_alter_tache_parent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("RLD", "Rld"), ("V", "V")],
                max_length=100,
                null=True,
            ),
        ),
    ]
