# Generated by Django 5.1.6 on 2025-03-07 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0008_tache_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tache",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="tache",
            name="parent_id",
        ),
        migrations.RemoveField(
            model_name="tache",
            name="parent_type",
        ),
    ]
