# Generated by Django 5.1.6 on 2025-03-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "planification",
            "0009_remove_tache_object_id_remove_tache_parent_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="type",
            field=models.TextField(
                blank=True, choices=[("RLD", "Rld"), ("V", "V")], null=True
            ),
        ),
    ]
