# Generated by Django 5.1.6 on 2025-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0010_alter_tache_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="label",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tache",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("RLD", "Rld"), ("V", "V")],
                max_length=100,
                null=True,
            ),
        ),
    ]
