# Generated by Django 5.1.6 on 2025-03-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0011_alter_tache_label_alter_tache_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="label",
            field=models.TextField(),
        ),
    ]
