# Generated by Django 5.1.6 on 2025-03-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0012_alter_tache_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="decaissement",
            name="tache",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.tache",
            ),
        ),
    ]
