# Generated by Django 5.1.6 on 2025-03-08 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_departement"),
        ("planification", "0013_decaissement_tache"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indicateur",
            options={"ordering": ("pk",)},
        ),
        migrations.AddField(
            model_name="tache",
            name="departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.departement",
            ),
        ),
    ]
