# Generated by Django 5.1.6 on 2025-03-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0014_alter_indicateur_options_tache_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="frequence",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
