# Generated by Django 5.1.6 on 2025-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0015_alter_tache_frequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="status_validation",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
