# Generated by Django 5.1.6 on 2025-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0017_decaissement_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicateur",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("ILD", "Ild"), ("HORS ILD", "Hors Ild")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tache",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("RLD", "Rld"), ("HORS_RLD", "Hors Rld")],
                max_length=100,
                null=True,
            ),
        ),
    ]
