# Generated by Django 5.1.6 on 2025-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0022_planificationcout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="depends_on",
            field=models.ManyToManyField(blank=True, to="planification.tache"),
        ),
    ]
