# Generated by Django 5.1.6 on 2025-03-14 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0023_alter_tache_depends_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tache",
            name="unite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.typeunite",
            ),
        ),
    ]
