# Generated by Django 5.1.6 on 2025-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0024_alter_tache_unite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicateur",
            name="label",
            field=models.TextField(),
        ),
    ]
