# Generated by Django 5.1.6 on 2025-03-16 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0025_alter_indicateur_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuitechnique",
            name="sous_composant",
        ),
        migrations.RemoveField(
            model_name="ild",
            name="sous_composant",
        ),
        migrations.RemoveField(
            model_name="rld",
            name="ild",
        ),
        migrations.DeleteModel(
            name="Activite",
        ),
        migrations.DeleteModel(
            name="AppuiTechnique",
        ),
        migrations.DeleteModel(
            name="ILD",
        ),
        migrations.DeleteModel(
            name="RLD",
        ),
    ]
