# Generated by Django 5.1.6 on 2025-10-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercice'),
        ('planification', '0026_remove_appuitechnique_sous_composant_and_more'),
        ('programme', '0014_alter_planificationcoutprogram_exercice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificationcout',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercice'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice'),
        ),
        migrations.CreateModel(
            name='Drf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('label', models.TextField(blank=True, null=True)),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice')),
            ],
        ),
        migrations.AddField(
            model_name='decaissement',
            name='drf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planification.drf'),
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
    ]
