# Generated by Django 5.1.6 on 2025-10-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exercice_file_alter_exercice_label'),
        ('planification', '0027_alter_planificationcout_exercice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decaissement',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice'),
        ),
    ]
