# Generated by Django 5.1.6 on 2025-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0028_decaissement_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='decaissement',
            name='motif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
