# Generated by Django 5.1.6 on 2025-10-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0029_decaissement_motif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drf',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
