# Generated by Django 5.1.6 on 2025-04-27 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('marque', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=100)),
                ('numero_chassis', models.CharField(max_length=100)),
                ('entretients', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpruntVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sortie', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('nom_chauffeur', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('km_in', models.PositiveIntegerField(default=0)),
                ('km_out', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='En poul', max_length=100)),
                ('is_panne', models.BooleanField(default=False)),
                ('type_panne', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.vehicule')),
            ],
        ),
    ]
