# Generated by Django 5.1.6 on 2025-05-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
