# Generated by Django 5.1.6 on 2025-05-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_vehicule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empruntvehicule',
            name='km_in',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empruntvehicule',
            name='km_out',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
