# Generated by Django 5.1.6 on 2025-05-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_empruntvehicule_km_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empruntvehicule',
            name='status',
            field=models.CharField(blank=True, default='En poul', max_length=100, null=True),
        ),
    ]
