# Generated by Django 5.1.6 on 2025-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_empruntvehicule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='status',
            field=models.CharField(blank=True, default='disponible', max_length=100),
        ),
    ]
