# Generated by Django 5.1.6 on 2025-05-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_alter_vehicule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='entretients',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
