# Generated by Django 5.1.6 on 2025-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_alter_vehicule_entretients'),
    ]

    operations = [
        migrations.AddField(
            model_name='empruntvehicule',
            name='destination',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empruntvehicule',
            name='type_sortie',
            field=models.CharField(choices=[('mission', 'Mission'), ('course', 'Course'), ('deplacement', 'Deplacement')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empruntvehicule',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empruntvehicule',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom & prenoms Responsable'),
        ),
        migrations.AlterField(
            model_name='empruntvehicule',
            name='type_panne',
            field=models.CharField(blank=True, choices=[('panne_seche', 'Panne séche'), ('crevaison', 'Crevaison'), ('Pièces retirée', 'Pièce Retirer'), ('autres', 'Autres')], max_length=100, null=True, verbose_name='Incidents'),
        ),
    ]
