# Generated by Django 5.1.6 on 2025-03-13 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0023_alter_tache_depends_on"),
        ("suivi", "0002_tdr_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tdr",
            name="activity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.tache",
                verbose_name="Activité",
            ),
        ),
    ]
