# Generated by Django 5.1.6 on 2025-03-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planification", "0025_alter_indicateur_label"),
        ("suivi", "0003_alter_tdr_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tdr",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planification.tache",
                verbose_name="Activité",
            ),
        ),
    ]
