# Generated by Django 5.1.6 on 2025-03-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0013_composantesprogram_sous_domain"),
        ("suivi", "0005_tdrprogramme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tdrprogramme",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="programme.tacheprogram",
                verbose_name="Activité",
            ),
        ),
    ]
