# Generated by Django 5.1.7 on 2025-03-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programme", "0013_composantesprogram_sous_domain"),
        ("suivi", "0006_alter_tdrprogramme_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tdrprogramme",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="programme.activite",
                verbose_name="Activité",
            ),
        ),
    ]
