# Generated by Django 5.1.7 on 2025-03-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("suivi", "0007_alter_tdrprogramme_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentairetdr",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentairetdr",
            name="tdr",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
