# Generated by Django 5.1.7 on 2025-03-23 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0008_commentairetdr_object_id_alter_commentairetdr_tdr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentairetdr",
            old_name="tdr",
            new_name="content_type",
        ),
    ]
