# Generated by Django 5.1.7 on 2025-03-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0010_tdr_file_final_tdrprogramme_file_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="tdr",
            name="lessons",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tdr",
            name="recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tdr",
            name="risks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tdrprogramme",
            name="lessons",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tdrprogramme",
            name="recommendations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tdrprogramme",
            name="risks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
