# Generated by Django 5.1.7 on 2025-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suivi", "0011_tdr_lessons_tdr_recommendations_tdr_risks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tdr",
            name="accorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tdr",
            name="injonction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tdrprogramme",
            name="accorder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tdrprogramme",
            name="injonction",
            field=models.BooleanField(default=False),
        ),
    ]
