# Generated by Django 5.1.6 on 2025-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0012_tdr_accorder_tdr_injonction_tdrprogramme_accorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdr',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tdrprogramme',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
