# Generated by Django 5.1.6 on 2025-10-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercice'),
        ('suivi', '0013_alter_tdr_label_alter_tdrprogramme_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdr',
            name='departemnt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departement'),
        ),
        migrations.AddField(
            model_name='tdr',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.exercice'),
        ),
    ]
